force-app/main/default/objects/DDRL_Action_Button__c/DDRL_Action_Button__c.object-meta.xml
<CustomObject>
    <label>DDRL Action Button</label>
    <nameField>
        <label>Action Button Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DDRL Action Buttons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DDRL_Action_Button__c/fields/actionType__c.field-meta.xml
<CustomField>
    <fullName>actionType__c</fullName>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/configId__c.field-meta.xml
<CustomField>
    <fullName>configId__c</fullName>
    <label>DDRL Config</label>
    <referenceTo>DDRL_Config__c</referenceTo>
    <relationshipLabel>DDRL Action Buttons</relationshipLabel>
    <relationshipName>DCRL_Action_Buttons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/horizontalPadding__c.field-meta.xml
<CustomField>
    <fullName>horizontalPadding__c</fullName>
    <label>Horizontal Padding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>XXX-Small</fullName>
            </value>
            <value>
                <fullName>XX-Small</fullName>
            </value>
            <value>
                <fullName>X-Small</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>X-Large</fullName>
            </value>
            <value>
                <fullName>XX-Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/iconName__c.field-meta.xml
<CustomField>
    <fullName>iconName__c</fullName>
    <label>Button Icon</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/iconPosition__c.field-meta.xml
<CustomField>
    <fullName>iconPosition__c</fullName>
    <label>Icon Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Left</fullName>
                <default>true</default>
                <label>Left</label>
            </value>
            <value>
                <fullName>Right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/showIcon__c.field-meta.xml
<CustomField>
    <fullName>showIcon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Icon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/tabIndex__c.field-meta.xml
<CustomField>
    <fullName>tabIndex__c</fullName>
    <label>Tab Index</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/variant__c.field-meta.xml
<CustomField>
    <fullName>variant__c</fullName>
    <label>Button Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Outline-Brand</fullName>
            </value>
            <value>
                <fullName>Inverse</fullName>
            </value>
            <value>
                <fullName>Destructive</fullName>
            </value>
            <value>
                <fullName>Text-Destructive</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/DDRL_Column__c.object-meta.xml
<CustomObject>
    <label>DDRL Column</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DDRL Columns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DDRL_Column__c/fields/config__c.field-meta.xml
<CustomField>
    <fullName>config__c</fullName>
    <label>DDRL Config</label>
    <referenceTo>DDRL_Config__c</referenceTo>
    <relationshipLabel>DDRL Columns</relationshipLabel>
    <relationshipName>DCRL_Columns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/day__c.field-meta.xml
<CustomField>
    <fullName>day__c</fullName>
    <label>Day Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/displayType__c.field-meta.xml
<CustomField>
    <fullName>displayType__c</fullName>
    <label>Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/hour__c.field-meta.xml
<CustomField>
    <fullName>hour__c</fullName>
    <label>Hour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/isLink__c.field-meta.xml
<CustomField>
    <fullName>isLink__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/label__c.field-meta.xml
<CustomField>
    <fullName>label__c</fullName>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/linkFormat__c.field-meta.xml
<CustomField>
    <fullName>linkFormat__c</fullName>
    <label>Link Format</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/minute__c.field-meta.xml
<CustomField>
    <fullName>minute__c</fullName>
    <label>Minute</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/month__c.field-meta.xml
<CustomField>
    <fullName>month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
            <value>
                <fullName>narrow</fullName>
            </value>
            <value>
                <fullName>short</fullName>
            </value>
            <value>
                <fullName>long</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <label>Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/second__c.field-meta.xml
<CustomField>
    <fullName>second__c</fullName>
    <label>Second</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/timeZone__c.field-meta.xml
<CustomField>
    <fullName>timeZone__c</fullName>
    <inlineHelpText>Long TZ Identifier for the time zone to display the date time field in.  Refer to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for all time zones.  NB: abbreviations like GMT+11 don&apos;t work.</inlineHelpText>
    <label>Time Zone</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/year__c.field-meta.xml
<CustomField>
    <fullName>year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>numeric</fullName>
                <default>true</default>
                <label>numeric</label>
            </value>
            <value>
                <fullName>2-digit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/DDRL_Config__c.object-meta.xml
<CustomObject>
    <label>DD Related List Config</label>
    <nameField>
        <label>Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DD Related List Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DDRL_Config__c/fields/dcObjectName__c.field-meta.xml
<CustomField>
    <fullName>dcObjectName__c</fullName>
    <inlineHelpText>The Data Cloud (or other) object that you&apos;re retrieving in this related list</inlineHelpText>
    <label>Object Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/orderByClause__c.field-meta.xml
<CustomField>
    <fullName>orderByClause__c</fullName>
    <inlineHelpText>eg. ORDER BY ssot__Id__c ASC.  Must include &quot;ORDER BY&quot;.  You can optionally include a LIMIT clause after the ORDER BY.  eg. ORDER BY ssot__CreatedDate__c DESC LIMIT 10.</inlineHelpText>
    <label>ORDER BY Clause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/parentIdentifierField__c.field-meta.xml
<CustomField>
    <fullName>parentIdentifierField__c</fullName>
    <inlineHelpText>For Child Related Lists, this field is the field ON THE PARENT RECORD that stores its own unique / primary key.</inlineHelpText>
    <label>Parent&apos;s Primary Key Field</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/parentIdentifierThisObject__c.field-meta.xml
<CustomField>
    <fullName>parentIdentifierThisObject__c</fullName>
    <inlineHelpText>The field on the object that relates to the parent record - which might be the contact/individual, or a different CRM or DC record. For a Child Related List called Order Lines, the Parent Id Field might be Order_Id__c.</inlineHelpText>
    <label>Parent Id Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/selectStatement__c.field-meta.xml
<CustomField>
    <fullName>selectStatement__c</fullName>
    <inlineHelpText>The SELECT and FROM portions of a SQL or SOQL select statement.</inlineHelpText>
    <label>SELECT Statement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/uidField__c.field-meta.xml
<CustomField>
    <fullName>uidField__c</fullName>
    <inlineHelpText>Field that will contain the unique/primary Id of the displayed records.  For an Orders related list, the Primary Key Field might be Order_Id__c</inlineHelpText>
    <label>Primary Key Field</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DDRL_Unit_Tests.cls
@isTest
public class DDRL_Unit_Tests {

    @testSetup static void testSetup() {
        
        Account a = new Account();
        a.Name = 'Test';
        insert(a);
        
        Contact ct = new Contact();
        ct.FirstName = 'Test';
        ct.LastName = 'Test';
        ct.AccountId = a.Id;
        insert(ct);
        
        Case c = new Case();
        c.Subject = 'Test';
        c.ContactId = ct.Id;
        c.AccountId = a.Id;
        insert(c);
        
        CaseComment cc1 = new CaseComment();
        cc1.ParentId = c.Id;
        cc1.CommentBody = 'Test Comment 1';
        insert(cc1);
        
        CaseComment cc2 = new CaseComment();
        cc2.ParentId = c.Id;
        cc2.CommentBody = 'Test Comment 2';
        insert(cc2);
        
        Case c2 = new Case();
        c2.Subject = 'Test2';
        c2.ContactId = ct.Id;
        c2.AccountId = a.Id;
        insert(c2);
        
        DDRL_Config__c config = new DDRL_Config__c();
        config.Name = 'Test Config';
        config.dcObjectName__c = 'Case';
        config.uidField__c = 'Id';
        config.selectStatement__c = 'SELECT Id, Subject, Status, Priority, CreatedDate FROM Case';
        config.orderByClause__c = 'ORDER BY CreatedDate DESC LIMIT 5';
        config.parentIdentifierField__c = 'Id';
        config.parentIdentifierThisObject__c = 'Id';
        insert(config);
        
        DDRL_Column__c col1 = new DDRL_Column__c();
        col1.Name = 'Subject';
        col1.label__c = 'Subject';
        col1.isLink__c = true;
        col1.config__c = config.Id;
        col1.linkFormat__c = '/lightning/r/Case/{{Id}}/view';
        col1.order__c = 10;
        col1.type__c = 'Text';
        col1.displayType__c = 'Text';
        insert(col1);
        
        DDRL_Column__c col2 = new DDRL_Column__c();
        col2.Name='Status';
        col2.label__c = 'Status';
        col2.isLink__c = false;
        col2.config__c = config.Id;
        col2.order__c = 20;
        col2.type__c = 'Text';
        col2.displayType__c = 'Text';
        insert(col2);
        
        DDRL_Column__c col3 = new DDRL_Column__c();
        col3.Name='CreatedDate';
        col3.label__c = 'Created Date';
        col3.isLink__c = false;
        col3.config__c = config.Id;
        col3.order__c = 30;
        col3.type__c = 'DateTime';
        col3.displayType__c = 'DateTime';
        col3.day__c = '2-digit';
        col3.month__c = '2-digit';
        col3.year__c = 'numeric';
        col3.hour__c = 'numeric';
        col3.minute__c = '2-digit';
        col3.second__c = '';
        col3.timeZone__c = 'America/Los_Angeles';
        insert(col3);
        
        DDRL_Action_Button__c action1 = new DDRL_Action_Button__c();
        action1.Name = 'Test Action';
        action1.variant__c = 'Brand';
        action1.showIcon__c = true;
        action1.iconPosition__c = 'Left';
        action1.iconName__c = 'utility:close';
        action1.tabIndex__c = -1;
        action1.horizontalPadding__c = 'xx-small';
        action1.actionType__c = 'Flow';
        action1.action__c = 'Test';
        action1.configId__c = config.Id;
		insert(action1);
        
        DDRL_Config__c config2 = new DDRL_Config__c();
        config2.Name = 'Test Config2';
        config2.dcObjectName__c = 'CaseComment';
        config2.uidField__c = 'Id';
        config2.selectStatement__c = 'SELECT Id, CommentBody, CreatedDate FROM CaseComment';
        config2.orderByClause__c = 'ORDER BY CreatedDate DESC LIMIT 5';
        config2.parentIdentifierField__c = 'Id';
        config2.parentIdentifierThisObject__c = 'ParentId';
        insert(config2);
        
        DDRL_Column__c col21 = new DDRL_Column__c();
        col21.Name = 'CommentBody';
        col21.label__c = 'Comment';
        col21.isLink__c = true;
        col21.config__c = config2.Id;
        col21.linkFormat__c = '/lightning/r/CaseComment/{{Id}}/view';
        col21.order__c = 10;
        col21.type__c = 'Text';
        col21.displayType__c = 'Text';
        insert(col21);
        
        DDRL_Column__c col22 = new DDRL_Column__c();
        col22.Name='CreatedDate';
        col22.label__c = 'Created Date';
        col22.isLink__c = false;
        col22.config__c = config2.Id;
        col22.order__c = 30;
        col22.type__c = 'DateTime';
        col22.displayType__c = 'DateTime';
        col22.day__c = '2-digit';
        col22.month__c = '2-digit';
        col22.year__c = 'numeric';
        col22.hour__c = 'numeric';
        col22.minute__c = '2-digit';
        col22.second__c = '';
        col22.timeZone__c = 'America/Los_Angeles';
        insert(col22);
        
    }

    
    @isTest static void TestRelatedList() {
        
        DDRL_Config__c config = [SELECT Id FROM DDRL_Config__c WHERE Name='Test Config'];
        Case c = [SELECT Id FROM Case WHERE Subject='Test'];

        Test.startTest();
        DDRL_Related_List_Controller.RecordResponse response = DDRL_Related_List_Controller.getRelatedList(c.Id, config.Id, 'Case', 'Salesforce_00DDn00000Dv8Sx', 'Contact', 'IndividualIdentityLink__dlm', 'Contact.Account.Id');
        Test.stopTest();
        
    }
    
    @isTest static void TestFilteredRelatedList() {

        DDRL_Config__c config = [SELECT Id FROM DDRL_Config__c WHERE Name='Test Config'];
        Case c = [SELECT Id FROM Case WHERE Subject='Test'];

        Test.startTest();
        DDRL_Filtered_Related_List_Controller.RecordResponse response = DDRL_Filtered_Related_List_Controller.getRelatedList(c.Id, config.Id, 'Case', 'Salesforce_00DDn00000Dv8Sx', 'Contact', 'IndividualIdentityLink__dlm', 'Contact.Account.Id');

        String filters = '{"startDate":"2024-01-01","test1__c":null,"test2__c":null,"endDate":"2024-04-30"}';
        
        String filteredRecords = DDRL_Filtered_Related_List_Controller.filterQueryRecords(response.recordQuery, filters, 'CreatedDate');

        Test.stopTest();
        
    }
    
    @isTest static void TestChildRelatedList() {
        
        DDRL_Config__c config = [SELECT Id FROM DDRL_Config__c WHERE Name='Test Config2'];
        Case c = [SELECT Id FROM Case WHERE Subject='Test'];

        Test.startTest();
        DDRL_Child_Related_List_Controller.RecordResponse response = DDRL_Child_Related_List_Controller.getChildRelatedList(c.Id, 'Case', config.Id);
        Test.stopTest();
        
    }
    
    @isTest static void TestActionButtons() {
        
        DDRL_Config__c config = [SELECT Id FROM DDRL_Config__c WHERE Name='Test Config'];

        Test.startTest();
        String buttons = DDRL_Action_Buttons_Controller.GetButtons(config.Id);
        Test.stopTest();

    }
    

}