force-app/main/default/objects/DDRL_Action_Button__c/DDRL_Action_Button__c.object-meta.xml
<CustomObject>
    <label>DDRL Action Button</label>
    <nameField>
        <label>Action Button Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DDRL Action Buttons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DDRL_Action_Button__c/fields/actionType__c.field-meta.xml
<CustomField>
    <fullName>actionType__c</fullName>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/configId__c.field-meta.xml
<CustomField>
    <fullName>configId__c</fullName>
    <label>DDRL Config</label>
    <referenceTo>DDRL_Config__c</referenceTo>
    <relationshipLabel>DDRL Action Buttons</relationshipLabel>
    <relationshipName>DCRL_Action_Buttons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/horizontalPadding__c.field-meta.xml
<CustomField>
    <fullName>horizontalPadding__c</fullName>
    <label>Horizontal Padding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>XXX-Small</fullName>
            </value>
            <value>
                <fullName>XX-Small</fullName>
            </value>
            <value>
                <fullName>X-Small</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>X-Large</fullName>
            </value>
            <value>
                <fullName>XX-Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/iconName__c.field-meta.xml
<CustomField>
    <fullName>iconName__c</fullName>
    <label>Button Icon</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/iconPosition__c.field-meta.xml
<CustomField>
    <fullName>iconPosition__c</fullName>
    <label>Icon Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Left</fullName>
                <default>true</default>
                <label>Left</label>
            </value>
            <value>
                <fullName>Right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/showIcon__c.field-meta.xml
<CustomField>
    <fullName>showIcon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Icon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/tabIndex__c.field-meta.xml
<CustomField>
    <fullName>tabIndex__c</fullName>
    <label>Tab Index</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DDRL_Action_Button__c/fields/variant__c.field-meta.xml
<CustomField>
    <fullName>variant__c</fullName>
    <label>Button Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Outline-Brand</fullName>
            </value>
            <value>
                <fullName>Inverse</fullName>
            </value>
            <value>
                <fullName>Destructive</fullName>
            </value>
            <value>
                <fullName>Text-Destructive</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DDRL_Action_Buttons_Controller.cls
public class DDRL_Action_Buttons_Controller {

    @AuraEnabled(cacheable=true)
    public static String getButtons(String configId) {
        
        RecordResponse resp = new RecordResponse();
        resp.buttons = [SELECT Id,
                        		Name,
                        		variant__c,
                        		showIcon__c,
                        		iconName__c,
                        		iconPosition__c,
                        		tabIndex__c,
                        		horizontalPadding__c,
                        		actionType__c,
                                action__c
                           FROM DDRL_Action_Button__c
                          WHERE configId__c = :configId
                       ORDER BY tabIndex__c ASC];
        
        System.debug(resp.buttons);
        
        return JSON.serialize(resp);
    }
    
    public class RecordResponse {
        @AuraEnabled public List<DDRL_Action_Button__c> buttons;
    }
    
}