force-app/main/default/objects/DDRL_Column__c/DDRL_Column__c.object-meta.xml
<CustomObject>
    <label>DDRL Column</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DDRL Columns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DDRL_Column__c/fields/alignment__c.field-meta.xml
<CustomField>
    <fullName>alignment__c</fullName>
    <label>Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>left</fullName>
            </value>
            <value>
                <fullName>center</fullName>
            </value>
            <value>
                <fullName>right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/config__c.field-meta.xml
<CustomField>
    <fullName>config__c</fullName>
    <label>DDRL Config</label>
    <referenceTo>DDRL_Config__c</referenceTo>
    <relationshipLabel>DDRL Columns</relationshipLabel>
    <relationshipName>DCRL_Columns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/currencyCode__c.field-meta.xml
<CustomField>
    <fullName>currencyCode__c</fullName>
    <label>Currency Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/day__c.field-meta.xml
<CustomField>
    <fullName>day__c</fullName>
    <label>Day Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/decimalPlaces__c.field-meta.xml
<CustomField>
    <fullName>decimalPlaces__c</fullName>
    <label>Decimal Places</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/displayType__c.field-meta.xml
<CustomField>
    <fullName>displayType__c</fullName>
    <label>Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/hour__c.field-meta.xml
<CustomField>
    <fullName>hour__c</fullName>
    <label>Hour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/isLink__c.field-meta.xml
<CustomField>
    <fullName>isLink__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/label__c.field-meta.xml
<CustomField>
    <fullName>label__c</fullName>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/linkFormat__c.field-meta.xml
<CustomField>
    <fullName>linkFormat__c</fullName>
    <label>Link Format</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/minute__c.field-meta.xml
<CustomField>
    <fullName>minute__c</fullName>
    <label>Minute</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/month__c.field-meta.xml
<CustomField>
    <fullName>month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
            <value>
                <fullName>narrow</fullName>
            </value>
            <value>
                <fullName>short</fullName>
            </value>
            <value>
                <fullName>long</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <label>Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/second__c.field-meta.xml
<CustomField>
    <fullName>second__c</fullName>
    <label>Second</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/timeZone__c.field-meta.xml
<CustomField>
    <fullName>timeZone__c</fullName>
    <inlineHelpText>Long TZ Identifier for the time zone to display the date time field in.  Refer to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for all time zones.  NB: abbreviations like GMT+11 don&apos;t work.</inlineHelpText>
    <label>Time Zone</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/width__c.field-meta.xml
<CustomField>
    <fullName>width__c</fullName>
    <label>Width (px)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/wrapText__c.field-meta.xml
<CustomField>
    <fullName>wrapText__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wrap Long Text Fields</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/year__c.field-meta.xml
<CustomField>
    <fullName>year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>numeric</fullName>
                <default>true</default>
                <label>numeric</label>
            </value>
            <value>
                <fullName>2-digit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/DDRL_Config__c.object-meta.xml
<CustomObject>
    <label>DD Related List Config</label>
    <nameField>
        <label>Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DD Related List Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DDRL_Config__c/fields/additionalWhereClause__c.field-meta.xml
<CustomField>
    <fullName>additionalWhereClause__c</fullName>
    <inlineHelpText>The SQL/SOQL will automatically be scoped to the unified individual.  Additional filters can be applied here. eg. ssot__CaseStatusId__c != &apos;Closed&apos;.  Don&apos;t include WHERE at the front.</inlineHelpText>
    <label>Additional WHERE Clauses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/dcObjectName__c.field-meta.xml
<CustomField>
    <fullName>dcObjectName__c</fullName>
    <inlineHelpText>The Data Cloud (or other) object that you&apos;re retrieving in this related list</inlineHelpText>
    <label>Object Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/keyQualifierField__c.field-meta.xml
<CustomField>
    <fullName>keyQualifierField__c</fullName>
    <inlineHelpText>If KQ fields are used, specify the KQ field on this object here.</inlineHelpText>
    <label>Key Qualifier Field</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/orderByClause__c.field-meta.xml
<CustomField>
    <fullName>orderByClause__c</fullName>
    <inlineHelpText>eg. ORDER BY ssot__Id__c ASC.  Must include &quot;ORDER BY&quot;.  You can optionally include a LIMIT clause after the ORDER BY.  eg. ORDER BY ssot__CreatedDate__c DESC LIMIT 10.</inlineHelpText>
    <label>ORDER BY Clause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/parentIdentifierField__c.field-meta.xml
<CustomField>
    <fullName>parentIdentifierField__c</fullName>
    <inlineHelpText>For Child Related Lists, this field is the field ON THE PARENT RECORD that stores its own unique / primary key.</inlineHelpText>
    <label>Parent&apos;s Primary Key Field</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/parentIdentifierThisObject__c.field-meta.xml
<CustomField>
    <fullName>parentIdentifierThisObject__c</fullName>
    <inlineHelpText>The field on the object that relates to the parent record - which might be the contact/individual, or a different CRM or DC record. For a Child Related List called Order Lines, the Parent Id Field might be Order_Id__c.</inlineHelpText>
    <label>Parent Id Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/selectStatement__c.field-meta.xml
<CustomField>
    <fullName>selectStatement__c</fullName>
    <inlineHelpText>The SELECT and FROM portions of a SQL or SOQL select statement.</inlineHelpText>
    <label>SELECT Statement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/uidField__c.field-meta.xml
<CustomField>
    <fullName>uidField__c</fullName>
    <inlineHelpText>Field that will contain the unique/primary Id of the displayed records.  For an Orders related list, the Primary Key Field might be Order_Id__c</inlineHelpText>
    <label>Primary Key Field</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DDRL_Child_Related_List_Controller.cls
public class DDRL_Child_Related_List_Controller {

    @AuraEnabled(cacheable=true)
    public static RecordResponse getChildRelatedList(String recordId, String objectApiName, String configId) {
        
        DDRL_Config__c config = [SELECT Id,
                                        Name,
                                        dcObjectName__c,
                                 		parentIdentifierField__c,
                                 		parentIdentifierThisObject__c,
                                        keyQualifierField__c,
                                 		selectStatement__c,
                                 		additionalWhereClause__c,
                                 		orderByClause__c,
                                        uidField__c
                                   FROM DDRL_Config__c 
                                  WHERE Id=:configId];
        
        List<DDRL_Column__c> columns = [SELECT Id,
                                               Name,
                                               label__c,
                                               type__c,
                                               displayType__c,
                                               decimalPlaces__c,
                                               currencyCode__c,
                                               day__c,
                                               month__c,
                                               year__c,
                                        	   hour__c,
                                               minute__c,
                                               second__c,
                                               timeZone__c,
                                               order__c,
                                               alignment__c,
                                               width__c,
                                        	   wrapText__c,
                                        	   isLink__c,
                                               linkFormat__c
                                          FROM DDRL_Column__c
                                         WHERE config__c = :configId
                                      ORDER BY order__c ASC];
        
        Set<String> selectFields = new Set<String>{ 'Id', config.parentIdentifierField__c };
        
        String parentQuery = 'SELECT '+String.join(selectFields, ',');
        Boolean hasKQField = false;
        if(!String.isBlank(config.keyQualifierField__c)) {
            hasKQField = true;
            parentQuery += ', '+config.keyQualifierField__c;
        }
        parentQuery += ' FROM '+objectApiName+' WHERE Id=\''+recordId+'\' LIMIT 1';
        
        System.debug('** Parent Query: '+parentQuery);

        sObject parentRecord = Database.query(parentQuery);
        
        System.debug('** Parent Record: '+parentRecord);
        
        ParentConfig pc = new ParentConfig();
        pc.recordId = recordId;
        pc.objectApiName = objectApiName;
        pc.idField = config.parentIdentifierField__c;
        pc.idValue = (String)parentRecord.get(config.parentIdentifierField__c);
        pc.hasKq = hasKQField;
        if(pc.hasKq) {
            pc.kqField = config.keyQualifierField__c;
            pc.kqValue = (String)parentRecord.get(config.keyQualifierField__c);
        }

        System.debug('Parent Identifier: '+pc.idValue);
        
        String records = queryRecords(pc, config);
        
        System.debug('Records: '+records);
        
        RecordResponse resp = new RecordResponse();
        resp.records = records;
        resp.columns = JSON.serialize(columns);
        resp.keyField = config.uidField__c;
        resp.config = JSON.serialize(config);
        resp.parentDcId = pc.idValue;
        
        System.debug(JSON.serialize(resp));
        
        return resp;

    }
    
    public static String queryRecords(ParentConfig pc, DDRL_Config__c config) {
        
        // Build Overall WHERE Clause
        String whereClause = ' WHERE ( ' + config.parentIdentifierThisObject__c + ' = \'' + pc.idValue + '\' ';
        if(pc.hasKq) whereClause += 'AND ' + pc.kqField + ' = \'' + pc.kqValue +'\' ';
        whereClause += ') ';
        
        if(!String.isBlank(config.additionalWhereClause__c)) whereClause += 'AND (' + config.additionalWhereClause__c + ') ';
        
        String query = config.selectStatement__c + whereClause + config.orderByClause__c;
        System.debug('**** Data Cloud Records SOQL Query: ' + query);
        
        List<sObject> sobjs = Database.query(query);
        
        String records = '[]';
        
        if(sobjs.size() > 0) {
            records = '[';
            Boolean first = true;
            for(sObject sobj : sobjs) {
                if(first) {
                    first = false;
                } else {
                    records += ', ';
                }
                records += JSON.serialize(sobj);
            }
            records += ']';
        }

        return records;
    }
    
    private class ParentConfig {
        private String idField;
        private String idValue;
        private Boolean hasKq;
        private String kqField;
        private String kqValue;
        private String recordId;
        private String objectApiName;
    }
    
    public class RecordResponse {
        @AuraEnabled public String records;
        @AuraEnabled public String columns;
        @AuraEnabled public String keyField;
        @AuraEnabled public String config;
        @AuraEnabled public String parentDcId;
    }
        
    
}