force-app/main/default/objects/DDRL_Column__c/DDRL_Column__c.object-meta.xml
<CustomObject>
    <label>DDRL Column</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DDRL Columns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DDRL_Column__c/fields/alignment__c.field-meta.xml
<CustomField>
    <fullName>alignment__c</fullName>
    <label>Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>left</fullName>
            </value>
            <value>
                <fullName>center</fullName>
            </value>
            <value>
                <fullName>right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/config__c.field-meta.xml
<CustomField>
    <fullName>config__c</fullName>
    <label>DDRL Config</label>
    <referenceTo>DDRL_Config__c</referenceTo>
    <relationshipLabel>DDRL Columns</relationshipLabel>
    <relationshipName>DCRL_Columns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/currencyCode__c.field-meta.xml
<CustomField>
    <fullName>currencyCode__c</fullName>
    <label>Currency Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/day__c.field-meta.xml
<CustomField>
    <fullName>day__c</fullName>
    <label>Day Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/decimalPlaces__c.field-meta.xml
<CustomField>
    <fullName>decimalPlaces__c</fullName>
    <label>Decimal Places</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/displayType__c.field-meta.xml
<CustomField>
    <fullName>displayType__c</fullName>
    <label>Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/hour__c.field-meta.xml
<CustomField>
    <fullName>hour__c</fullName>
    <label>Hour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/isLink__c.field-meta.xml
<CustomField>
    <fullName>isLink__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/label__c.field-meta.xml
<CustomField>
    <fullName>label__c</fullName>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/linkFormat__c.field-meta.xml
<CustomField>
    <fullName>linkFormat__c</fullName>
    <label>Link Format</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/minute__c.field-meta.xml
<CustomField>
    <fullName>minute__c</fullName>
    <label>Minute</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/month__c.field-meta.xml
<CustomField>
    <fullName>month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
            <value>
                <fullName>narrow</fullName>
            </value>
            <value>
                <fullName>short</fullName>
            </value>
            <value>
                <fullName>long</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <label>Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/second__c.field-meta.xml
<CustomField>
    <fullName>second__c</fullName>
    <label>Second</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2-digit</fullName>
                <default>true</default>
                <label>2-digit</label>
            </value>
            <value>
                <fullName>numeric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/timeZone__c.field-meta.xml
<CustomField>
    <fullName>timeZone__c</fullName>
    <inlineHelpText>Long TZ Identifier for the time zone to display the date time field in.  Refer to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for all time zones.  NB: abbreviations like GMT+11 don&apos;t work.</inlineHelpText>
    <label>Time Zone</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/width__c.field-meta.xml
<CustomField>
    <fullName>width__c</fullName>
    <label>Width (px)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/wrapText__c.field-meta.xml
<CustomField>
    <fullName>wrapText__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wrap Long Text Fields</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DDRL_Column__c/fields/year__c.field-meta.xml
<CustomField>
    <fullName>year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>numeric</fullName>
                <default>true</default>
                <label>numeric</label>
            </value>
            <value>
                <fullName>2-digit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/DDRL_Config__c.object-meta.xml
<CustomObject>
    <label>DD Related List Config</label>
    <nameField>
        <label>Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DD Related List Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DDRL_Config__c/fields/additionalWhereClause__c.field-meta.xml
<CustomField>
    <fullName>additionalWhereClause__c</fullName>
    <inlineHelpText>The SQL/SOQL will automatically be scoped to the unified individual.  Additional filters can be applied here. eg. ssot__CaseStatusId__c != &apos;Closed&apos;.  Don&apos;t include WHERE at the front.</inlineHelpText>
    <label>Additional WHERE Clauses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/dcObjectName__c.field-meta.xml
<CustomField>
    <fullName>dcObjectName__c</fullName>
    <inlineHelpText>The Data Cloud (or other) object that you&apos;re retrieving in this related list</inlineHelpText>
    <label>Object Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/keyQualifierField__c.field-meta.xml
<CustomField>
    <fullName>keyQualifierField__c</fullName>
    <inlineHelpText>If KQ fields are used, specify the KQ field on this object here.</inlineHelpText>
    <label>Key Qualifier Field</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/orderByClause__c.field-meta.xml
<CustomField>
    <fullName>orderByClause__c</fullName>
    <inlineHelpText>eg. ORDER BY ssot__Id__c ASC.  Must include &quot;ORDER BY&quot;.  You can optionally include a LIMIT clause after the ORDER BY.  eg. ORDER BY ssot__CreatedDate__c DESC LIMIT 10.</inlineHelpText>
    <label>ORDER BY Clause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/parentIdentifierThisObject__c.field-meta.xml
<CustomField>
    <fullName>parentIdentifierThisObject__c</fullName>
    <inlineHelpText>The field on the object that relates to the parent record - which might be the contact/individual, or a different CRM or DC record. For a Child Related List called Order Lines, the Parent Id Field might be Order_Id__c.</inlineHelpText>
    <label>Parent Id Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/selectStatement__c.field-meta.xml
<CustomField>
    <fullName>selectStatement__c</fullName>
    <inlineHelpText>The SELECT and FROM portions of a SQL or SOQL select statement.</inlineHelpText>
    <label>SELECT Statement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DDRL_Config__c/fields/uidField__c.field-meta.xml
<CustomField>
    <fullName>uidField__c</fullName>
    <inlineHelpText>Field that will contain the unique/primary Id of the displayed records.  For an Orders related list, the Primary Key Field might be Order_Id__c</inlineHelpText>
    <label>Primary Key Field</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DDRL_Related_List_Controller.cls
/*
 * Controller for the ddrlRelatedList LWC. The LWC can be added to any standard Salesforce record page.  It is not supported on a Data Cloud record page, instead use
 * the ddrlChildRelatedList component. This variant of the component is for use in Data Cloud host orgs, not orgs that connect soley via Data Cloud APIs.
 * 
 * The component uses Dynamic SOQL to query the Data Cloud linked profiles and records. In theory this should be faster and easier to maintain than API-based integration.
 * 
 */

public class DDRL_Related_List_Controller {

    @AuraEnabled(cacheable=true)
    public static RecordResponse getRelatedList(String recordId, String configId, String objectApiName, String dataSourceId, String dataSourceObjectId, String individualIdentityLinkObject, String recordContactField) {
        
        // The component is designed to be dropped onto any page that's linked to a contact/lead/other individual record.  The recordContactField parameter specifies the path to that record.
        // eg. on a case it might be ContactId. On a Work Order linked to that case it might be Case.ContactId. This routine navigates up the record hierarchy to ultimately find the
        // contact/lead/other's record Id.
        if(!String.isBlank(recordContactField) && recordContactField.toLowercase() != 'id') {
	        String recordQuery = 'SELECT '+recordContactField+' FROM '+objectApiName+' WHERE Id=\''+recordId+'\'';
            System.debug('**Record Query: '+recordQuery);
            SObject s = Database.query(recordQuery);
            List<String> fieldParts = recordContactField.split('\\.');
            while(fieldParts.size() > 1) {
      			s = s.getSObject(fieldParts.remove(0));
    		}
            recordId = (String)s.get(fieldParts[0]);
            System.debug(recordId);
        }
        
		// The config and columns records determine which fields will be queries and how columns should be displayed        
        DDRL_Config__c config = [SELECT Id,
                                        Name,
                                        dcObjectName__c,
                                 		parentIdentifierThisObject__c,
                                        keyQualifierField__c,
                                 		selectStatement__c,
                                 		additionalWhereClause__c,
                                 		orderByClause__c,
                                        uidField__c
                                   FROM DDRL_Config__c 
                                  WHERE Id=:configId];
        List<DDRL_Column__c> columns = [SELECT Id,
                                               Name,
                                               label__c,
                                               type__c,
                                               displayType__c,
                                               decimalPlaces__c,
                                               currencyCode__c,
                                               day__c,
                                               month__c,
                                               year__c,
                                        	   hour__c,
                                               minute__c,
                                               second__c,
                                               timeZone__c,
                                               order__c,
                                               alignment__c,
                                               width__c,
                                        	   wrapText__c,
                                        	   isLink__c,
                                               linkFormat__c
                                          FROM DDRL_Column__c
                                         WHERE config__c = :configId
                                      ORDER BY order__c ASC];
        
        // This method identifies all the linked individual records from different systems that make up this individuals unified profile.
        List<sObject> linkedIndividuals = getLinkedIndividuals(recordId, objectApiName, dataSourceId, dataSourceObjectId, individualIdentityLinkObject);

        // This method queries the Data Cloud object as specified in the config, restricting the query to only those records related to a linked individual
        String records = queryRecords(linkedIndividuals, config);
        
        RecordResponse resp = new RecordResponse();
        resp.records = records;
        resp.columns = JSON.serialize(columns);
        resp.keyField = config.uidField__c;
        
        return resp;
    }
    
    public static List<sObject> getLinkedIndividuals(String recordId, String objectApiName, String dataSourceId, String dataSourceObjectId, String individualIdentityLinkObject) {
        
        /* Commenting out to support non-B2C Orgs
        if(objectApiName == 'Account') {
            System.debug('recordId: '+recordId);
            Account a = [SELECT Id, IsPersonAccount, PersonContactId FROM Account WHERE Id=:recordId];
            System.debug('Account: '+a);
            if(a.isPersonAccount) recordId = a.PersonContactId;
        }
        */
        
        String individualQuery = 'SELECT UnifiedRecordId__c FROM '+individualIdentityLinkObject+' WHERE SourceRecordId__c=\''+recordId+'\' AND ssot__DataSourceId__c = \''+dataSourceId+'\' AND ssot__DataSourceObjectId__c = \''+dataSourceObjectId+'\' LIMIT 1';

        sObject individualLinkRecord;
        String unifiedRecordId;
        
        try {
            individualLinkRecord = Database.Query(individualQuery);
            unifiedRecordId = (String)individualLinkRecord.get('UnifiedRecordId__c');
        } catch(Exception e) {
            if(Test.isRunningTest()) {
                unifiedRecordId = recordId;
            }
        }
        
        List<sObject> linkedIndividuals = null;
        
        if(Test.isRunningTest()) {
            linkedIndividuals = Database.Query('SELECT Id FROM Account WHERE Id=\''+recordId+'\'');
        } else {
	        linkedIndividuals = Database.Query('SELECT UnifiedRecordId__c, ssot__DataSourceId__c, ssot__DataSourceObjectId__c, SourceRecordId__c, KQ_SourceRecordID__c FROM '+individualIdentityLinkObject+' WHERE UnifiedRecordId__c = \''+unifiedRecordId+'\'');            
        }

        
        System.debug('** Linked Individuals: '+linkedIndividuals);
        return linkedIndividuals;
        
    }
    
    public static String queryRecords(List<sObject> linkedIndividuals, DDRL_Config__c config) {
        
        // Build Overall WHERE Clause
        List<String> whereClauses = new List<String>();        
	    for(sObject ind : linkedIndividuals) {
            String wC = (!Test.isRunningTest()) ? '( ' + config.parentIdentifierThisObject__c + ' = \'' + (String)ind.get('SourceRecordId__c') + '\' ' : '( AccountId = \''+ind.get('Id')+'\' ';
            if(!String.isBlank(config.keyQualifierField__c)) wC += 'AND ' + config.keyQualifierField__c + ' = \'' + (String)ind.get('KQ_SourceRecordId__c') +'\' ';
            wC += ')';
            whereClauses.add(wC);
        }
        String whereClause = '';
        if(whereClauses.size() > 0) {
            whereClause += ' WHERE (' + String.join(whereClauses, ' OR ') + ') ';
            if(!String.isBlank(config.additionalWhereClause__c)) whereClause += 'AND (' + config.additionalWhereClause__c + ') ';
            
        	String query = config.selectStatement__c + whereClause + config.orderByClause__c;
        	System.debug('**** Data Cloud Records SOQL Query: ' + query);

            List<sObject> sobjs = Database.query(query);
            
            // No idea why, but lists of plain sObjects won't serialize to JSON strings.
            // So this routine loops through the returned records and serializes them one by one.
            String records = '[]';
            if(sobjs.size() >0) {
                records='[';
                Boolean first = true;
                for(SObject sobj : sobjs) {
                    if(first) {
                        first=false;
                    } else {
                        records += ', ';
                    }
                    records += JSON.serialize(sobj);
                }
                records += ']';
            }
            
            System.debug(records);
            return records;
        }
        
        return null;
    }
    
    public class RecordResponse {
        @AuraEnabled public String records;
        @AuraEnabled public String columns;
        @AuraEnabled public String keyField;
    }
        
    
}